# Production configuration for sample application

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proddb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:produser}
    password: ${DB_PASSWORD:prodpass}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.example: INFO
    org.springframework.web: WARN
  file:
    name: /var/log/myapp.log

app:
  name: Sample Application
  version: 1.0.0
  features:
    feature1: enabled
    feature2: enabled
