# Sample application configuration
# This is an example configuration file for a sample application

server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.example: DEBUG
    org.springframework.web: INFO

app:
  name: Sample Application
  version: 1.0.0
  features:
    feature1: enabled
    feature2: disabled
